### ISSUE TITLE
socket.io client 0.9.8 causes KeyError exceptions

### ISSUE THREAD

**Issue by dswarbrick** [abourget/gevent-socketio#63]
The socket.io client v0.9.8 released just yesterday is causing KeyError exceptions in gevent-socketio, when it disconnects/reconnects (eg. refresh a page, or even just leave a page that has a socketio connection).

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/talk2fs/talk2/core/views.py", line 42, in socketio_serve
    }, request)
  File "/usr/src/gevent-socketio/socketio/__init__.py", line 60, in socketio_manage
    socket = environ['socketio']
KeyError: 'socketio'
```

Other than that, it seems to be working fine.

**Comment by danmur** [comment]
This is still happening for me, even with the sample apps (at least the pyramid chat one). It's not on disconnect requests, it's on all requests. Downgrading the socket.io client to 0.9.something makes the problem go away.
