### ISSUE TITLE
WebSocketError not gracefully caught when client closes socket

### ISSUE THREAD

**Issue by dswarbrick** [abourget/gevent-socketio#78]
On a local development server, I've recently noticed that I get the following traceback if a socketio-enabled page is refreshed, closed, or I navigate somewhere else - basically, if the browser closes the underlying websocket connection:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/src/gevent-socketio/socketio/transports.py", line 241, in send_into_ws
    websocket.send(message)
  File "/usr/src/gevent-websocket/geventwebsocket/websocket.py", line 350, in send
    return self.send_frame(message, self.OPCODE_TEXT)
  File "/usr/src/gevent-websocket/geventwebsocket/websocket.py", line 314, in send_frame
    raise WebSocketError('The connection was closed')
WebSocketError: The connection was closed
<Greenlet at 0x467ff50: send_into_ws> failed with WebSocketError
```

Since gevent-websocket is probably correct in raising WebSocketErrror at line 314 of geventwebsocket/websocket.py (and may depend on that exception elsewhere), I think that gevent-socketio should catch that exception and gracefully dismiss it.

I have a feeling that this behaviour has only been in the last couple of weeks and wonder if it's related to recent commits. What seems a bit puzzling is that line 214 of socketio/transports.py is in the connect() method of WebsocketTransport. How can it be in the connect phase, if the socket has just been closed?

**Comment by dswarbrick** [comment]
Apologies for the lack of response. I haven't used gevent-socketio for many years, and it appears that the project is dormant / dead anyway. Feel free to re-open this issue if it sputters back to life and the problem still persists.
